# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-23 20:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Imdb',
            fields=[
                ('movieId', models.IntegerField(primary_key=True, serialize=False)),
                ('imdb', models.CharField(max_length=20)),
                ('tmdb', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movieId', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=1000)),
                ('genres', models.CharField(blank=True, max_length=1000)),
                ('year', models.IntegerField(blank=True, default=None)),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieId', models.IntegerField(default=None)),
                ('title', models.CharField(blank=True, max_length=1000)),
                ('genres', models.CharField(blank=True, max_length=1000)),
                ('year', models.IntegerField(blank=True, default=None)),
                ('url', models.URLField(blank=True)),
                ('rating', models.DecimalField(decimal_places=6, max_digits=10)),
                ('imdb', models.CharField(blank=True, max_length=100)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
